---
title: "CosMx_Analysis_060923"
output: html_document
date: "2023-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```







Load libraries
Load libraries
```{r load labraries}

library(Seurat)
library(future)
library(rgeos)
library(ggplot2)
library(rlang)
library(patchwork)
library(qrcode)
library(devtools)
library(InSituType)
library(readr)
library(RColorBrewer)
library(stringr)
library(ggplot2)
library(rgeos)
library(ggrepel)

set.seed(0)

```



Read in the data
```{r}


#dataset
seurat_object_3mon <- readRDS("seurat_object_3mon.rds")




```


Get Fig 8A

```{r}
#precalcualted setup files. To see how they are calculated see below code chunk. 
cohort_3mon <- readRDS("cohort_3mon.rds")
astats_3mon <- readRDS("astats_3mon.rds")
anchors <- readRDS("anchors.rds")



counts_3mon<-seurat_object_3mon@assays$Nanostring@counts
counts_3mon<-as.matrix(counts_3mon)
counts_3mon<-t(counts_3mon)
counts_3mon<-as.data.frame(counts_3mon)
ind_neg_3mon<-grep("Neg.*",colnames(counts_3mon))
negmean_3mon<-  Matrix::rowMeans(counts_3mon[,ind_neg_3mon])

Mos_Profile <- read_csv("Mos_Profile.csv")
Mos_Profile<-as.data.frame(Mos_Profile)
rownames(Mos_Profile)<-Mos_Profile$...1
Mos_Profile<-Mos_Profile[,-1]
Mos_Profile<-as.matrix(Mos_Profile)

counts_3mon<-as.matrix(counts_3mon)

sup_3mon <- insitutypeML(x = counts_3mon,
                    neg = negmean_3mon,
                    cohort = cohort_3mon,
                    reference_profiles = Mos_Profile,
                    nb_size= 10)   


colors<-c("blue","green","orange","purple", "forestgreen",
          "black", "pink", "dodgerblue", "cyan", "yellow",
          "firebrick1", "deepskyblue1", "darkolivegreen1", "gold", 
          "deeppink", "burlywood4", "tan3", "hotpink4","aquamarine", 
          "gray") 
names(colors)<-c("Oligo","L6b CTX","L5 PT CTX" ,"L5 IT CTX", "Sncg",
                 "Lamp5", "L6 CT CTX", "Astro",  "Sst" , "Pvalb" , 
                 "L6 IT CTX", "Sst Chodl", "Vip", "L2/3 IT PPP",
                 "L2/3 IT CTX", "L5/6 NP CTX","L4 RSP-ACA","Micro-PVM", "L5_6 IT TPE-ENT",
                 "Endo")

fp_color<-c(1:length(sup_3mon$clust))

for(i in unique(sup_3mon$clust)){
  print(i)
  ind<-which(sup_3mon$clust==i)
  if (length(grep(i,names(colors))) > 1){
    ind2<-which(grepl(i,names(colors)) & !grepl(" ",names(colors)))
  } else {
    ind2<-which(grepl(i,names(colors)))
  }
  vec<-colors[ind2]
  fp_color[ind]<-vec
}


colors[sup_3mon$clust]<-fp_color

fp_3mon <- flightpath_plot(flightpath_result = NULL, insitutype_result = sup_3mon, col = colors[sup_3mon$clust])
class(fp_3mon)
print(fp_3mon)

date_tag <- format(Sys.Date(), "%Y%m%d")

outdir <- paste0("output", date_tag)
dir.create(outdir,recursive = TRUE)

flightpath_plot_dir <-file.path(outdir, "flightpath", "Plots")
dir.create(flightpath_plot_dir,recursive = TRUE)


ggsave("flightpath_3mon.pdf", fp_3mon,  width = 20, height = 10, units = "cm",path = flightpath_plot_dir)



```


```{r}
#identify cohorts
immunofluordata_3mon <- rbind(seurat_object_3mon$Mean.Histone,seurat_object_3mon$Mean.G,seurat_object_3mon$Mean.rRNA,seurat_object_3mon$Mean.DAPI,seurat_object_3mon$Mean.GFAP)

rows<-c("Mean.Histone", "Mean.G","Mean.rRNA","Mean.DAPI","Mean.GFAP")

rownames(immunofluordata_3mon)<-rows

immunofluordata_3mon<-t(immunofluordata_3mon)

cohort_3mon <- fastCohorting(immunofluordata_3mon,
                        gaussian_transform = TRUE) 
table(cohort_3mon)
counts_3mon<-as.matrix(counts_3mon)
saveRDS(cohort_3mon, "cohort_3mon.rds")


# compute the statistics used to define anchor cells.
# (This step is slow for big datasets. It's recommended to run this once and save the results. 
# Then you can iteratively adjust your choices when selecting anchor cells)
astats_3mon <- get_anchor_stats(counts = counts_3mon,
                           neg = negmean_3mon,
                           profiles = Mos_Profile)


saveRDS(astats_3mon, "astats_3mon.rds")


# estimate per-cell bg as a fraction of total counts:
negmean.per.totcount_3mon <- mean(negmean_3mon) / mean(rowSums(counts_3mon))
per.cell.bg_3mon <- rowSums(counts_3mon) * negmean.per.totcount_3mon

# now choose anchors:
anchors <- choose_anchors_from_stats(counts = counts_3mon, 
                                     neg = negmean_3mon, 
                                     bg = per.cell.bg_3mon,
                                     anchorstats = astats_3mon, 
                                    
                                     n_cells = 400, 
                                     min_cosine = 0.4, 
                                     min_scaled_llr = 0.03, 
                                     insufficient_anchors_thresh = 5)





saveRDS(anchors, "anchors.rds")

```


Fig 8b and supplemental figure 17b, and c

Define function for visualizing cells
```{r}
imagecells<-function (object, fov = NULL, boundaries = NULL, group.by = NULL, 
          split.by = NULL, cols = NULL, shuffle.cols = FALSE, size = 0.5, 
          molecules = NULL, mols.size = 0.1, mols.cols = NULL, mols.alpha = 1, 
          nmols = 100000, alpha = 1, border.color = "white", border.size = NULL, 
          na.value = "grey50", dark.background = TRUE, crop = FALSE, 
          cells = NULL, overlap = FALSE, axes = FALSE, combine = TRUE, 
          coord.fixed = TRUE) 
{
  cells <- cells %||% Cells(x = object)
  fov <- fov %||% DefaultFOV(object = object)
  fov <- Filter(f = function(x) {
    return(x %in% Images(object = object) && inherits(x = object[[x]], 
                                                      what = "FOV"))
  }, x = fov)
  if (!length(x = fov)) {
    stop("No compatible spatial coordinates present")
  }
  boundaries <- boundaries %||% sapply(X = fov, FUN = function(x) {
    return(DefaultBoundary(object = object[[x]]))
  }, simplify = FALSE, USE.NAMES = TRUE)
  boundaries <- .BoundariesByImage(object = object, fov = fov, 
                                   boundaries = boundaries)
  fov <- names(x = boundaries)
  overlap <- rep_len(x = overlap, length.out = length(x = fov))
  crop <- rep_len(x = crop, length.out = length(x = fov))
  names(x = crop) <- fov
  group.by <- boundaries %!NA% group.by %||% "ident"
  vars <- c(group.by, split.by)
  md <- if (!is_na(x = vars)) {
    FetchData(object = object, vars = vars[!is.na(x = vars)], 
              cells = cells, slot="counts")
  }
  else {
    NULL
  }
  pnames <- unlist(x = lapply(X = seq_along(along.with = fov), 
                              FUN = function(i) {
                                return(if (isTRUE(x = overlap[i])) {
                                  fov[i]
                                } else {
                                  paste(fov[i], boundaries[[i]], sep = "_")
                                })
                              }))
  pdata <- vector(mode = "list", length = length(x = pnames))
  names(x = pdata) <- pnames
  for (i in names(x = pdata)) {
    ul <- unlist(x = strsplit(x = i, split = "_"))
    img <- paste(ul[1:length(ul) - 1], collapse = "_")
    lyr <- ul[length(ul)]
    if (is.na(x = lyr)) {
      lyr <- boundaries[[img]]
    }
    pdata[[i]] <- lapply(X = lyr, FUN = function(l) {
      if (l == "NA") {
        return(NA)
      }
      df <- fortify(model = object[[img]][[l]])
      df <- df[df$cell %in% cells, , drop = FALSE]
      if (!is.null(x = md)) {
        df <- merge(x = df, y = md, by.x = "cell", by.y = 0, 
                    all.x = TRUE)
      }
      df$cell <- paste(l, df$cell, sep = "_")
      df$boundary <- l
      return(df)
    })
    pdata[[i]] <- if (!is_na(x = pdata[[i]])) {
      do.call(what = "rbind", args = pdata[[i]])
    }
    else {
      unlist(x = pdata[[i]])
    }
  }
  if (!is.null(x = molecules)) {
    molecules <- .MolsByFOV(object = object, fov = fov, molecules = molecules)
    mdata <- vector(mode = "list", length = length(x = fov))
    names(x = mdata) <- fov
    for (img in names(x = mdata)) {
      idata <- object[[img]]
      if (!img %in% names(x = molecules)) {
        mdata[[img]] <- NULL
        next
      }
      if (isTRUE(x = crop[img])) {
        idata <- Overlay(x = idata, y = idata)
      }
      imols <- gsub(pattern = paste0("^", Key(object = idata)), 
                    replacement = "", x = molecules[[img]])
      mdata[[img]] <- FetchData(object = idata, vars = imols, 
                                nmols = nmols)
    }
  }
  else {
    mdata <- NULL
  }
  plots <- vector(mode = "list", length = length(x = pdata) * 
                    ifelse(test = length(x = group.by), yes = length(x = group.by), 
                           no = 1L))
  idx <- 1L
  for (group in group.by) {
    for (i in seq_along(along.with = pdata)) {
      img <- unlist(x = strsplit(x = names(x = pdata)[i], 
                                 split = "_"))[1L]
      p <- SingleImagePlot(data = pdata[[i]], col.by = pdata[[i]] %!NA% 
                             group, molecules = mdata[[img]], cols = cols, 
                           shuffle.cols = shuffle.cols, size = size, alpha = alpha, 
                           mols.size = mols.size, mols.cols = mols.cols, 
                           mols.alpha = mols.alpha, border.color = border.color, 
                           border.size = border.size, na.value = na.value, 
                           dark.background = dark.background)
      if (!is.null(x = split.by)) {
        p <- p + facet_wrap(facets = vars(!!sym(x = split.by)))
      }
      if (!isTRUE(x = axes)) {
        p <- p + NoAxes(panel.background = element_blank())
      }
      if (!anyDuplicated(x = pdata[[i]]$cell)) {
        p <- p + guides(fill = guide_legend(override.aes = list(size = 4L, 
                                                                alpha = 1)))
      }
      if (isTRUE(coord.fixed)) {
        p <- p + coord_fixed()
      }
      plots[[idx]] <- p
      idx <- idx + 1L
    }
  }
  if (isTRUE(x = combine)) {
    plots <- wrap_plots(plots)
  }
  return(plots)
}
```

``` {r} 
.BoundariesByImage <- function(object, fov, boundaries) {
  if (!is.list(x = boundaries)) {
    if (is.null(x = names(x = boundaries))) {
      boundaries <- rep_len(x = list(boundaries), length.out = length(x = fov))
      names(x = boundaries) <- fov
    } else {
      boundaries <- .AsList(x = boundaries)
    }
  }
  if (any(!nchar(x = names(x = boundaries)))) {
    missing <- setdiff(x = fov, y = names(x = boundaries))
    idx <- which(x = !nchar(x = names(x = boundaries)))
    boundaries <- c(
      boundaries[intersect(x = names(x = boundaries), y = fov)],
      rep_len(x = boundaries[idx], length.out = length(x = missing))
    )
    names(x = boundaries)[!nchar(x = names(x = boundaries))] <- missing
  }
  if (any(!fov %in% names(x = boundaries))) {
    for (i in setdiff(x = fov, y = names(x = boundaries))) {
      boundaries[[i]] <- Boundaries(object = object[[i]])[1L]
    }
  }
  fov <- union(x = fov, y = names(x = boundaries))
  if (length(x = boundaries) != length(x = fov)) {
    fov <- intersect(x = fov, y = names(x = boundaries))
  }
  boundaries <- boundaries[fov]
  for (i in fov) {
    boundaries[[i]] <- Filter(
      f = function(x) {
        return(x %in% Boundaries(object = object[[i]]) || is_na(x = x))
      },
      x = boundaries[[i]]
    )
  }
  boundaries <- Filter(f = length, x = boundaries)
  return(boundaries)
}

```


```{r}

#get all cells for that brain
p<-imagecells(object = seurat_object_3mon, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +xlim(c(20500,16000)) +
  ylim(c(-276000,-266000))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))

ggsave("IM149_roi56 .pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)

pSyn_positive_cells <- read.csv("pSyn_positive_cells.csv")

pSyn_cell_ind2<-which(seurat_object_3mon@meta.data$cell_ID %in% pSyn_positive_cells$TrueID==TRUE)
pSyn_cell_names2<- seurat_object_3mon@images$Run5738.msbrain@boundaries$centroids@cells[pSyn_cell_ind2]

#same brain psyn only
p<-imagecells(seurat_object_3mon, cells = pSyn_cell_names2, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))+xlim(c(20500,16000)) + ylim(c(-276000,-266000))

ggsave("IM149_roi56 _pSynOnly.pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)








#get all cells for that brain
p<-imagecells(seurat_object_3mon, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))+ xlim(c(20500,16000))  + ylim(c(-308000,-298000))  

ggsave("IM150_roi34.pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)

#same brain psyn only
p<-imagecells(seurat_object_3mon, cells = pSyn_cell_names2, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))+ xlim(c(20500,16000))  + ylim(c(-308000,-298000))  

ggsave("IM150_roi34_pSynOnly.pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)



#get all cells for that brain
p<-imagecells(seurat_object_3mon, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))+xlim(c(20500,16000)) + ylim(c(-341000,-332000)) 

ggsave("IM151_roi12.pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)

#same brain psyn only
p<-imagecells(seurat_object_3mon, cells = pSyn_cell_names2, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 1, axes = TRUE, border.color = NA,dark.background = FALSE,cols = colors) +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.size = unit(0.1,'cm'))+xlim(c(20500,16000)) + ylim(c(-341000,-332000))

ggsave("IM151_roi12_pSynOnly.pdf", p,  width = 10, height = 10, units = "cm", path = flightpath_plot_dir)


```

``` {r}

.MolsByFOV <- function(object, fov, molecules) {
  keys <- Key(object = object)[fov]
  keyed.mols <- sapply(
    X = names(x = keys),
    FUN = function(img) {
      if (is.null(x = Molecules(object = object[[img]]))) {
        return(NULL)
      }
      key <- keys[img]
      mols <- grep(pattern = paste0('^', key), x = molecules, value = TRUE)
      names(x = mols) <- mols
      mols <- gsub(pattern = paste0('^', key), replacement = '', x = mols)
      keyed <- sapply(
        X = SeuratObject::Keys(object = object[[img]]),
        FUN = function(x) {
          return(grep(pattern = paste0('^', x), x = mols, value = TRUE))
        }
      )
      keyed <- unlist(x = keyed)
      names(x = keyed) <- gsub(
        pattern = '^.*\\.',
        replacement = '',
        x = names(x = keyed)
      )
      missing <- mols[!mols %in% keyed]
      missing <- missing[missing %in% Features(x = object[[img]])]
      if (length(x = missing)) {
        # TODO: replace with default molecules
        default <- Molecules(object = object[[img]])[1L]
        mn <- names(x = missing)
        missing <- paste0(
          SeuratObject::Key(object = object[[img]][[default]]),
          missing
        )
        names(x = missing) <- mn
      }
      return(c(missing, keyed))
    },
    simplify = FALSE,
    USE.NAMES = TRUE
  )
  found <- names(x = unlist(x = keyed.mols))
  found <- gsub(pattern = '^.*\\.', replacement = '', x = found)
  missing <- setdiff(x = molecules, y = found)
  names(x = missing) <- missing
  for (img in fov) {
    imissing <- missing
    for (i in seq_along(along.with = imissing)) {
      for (lkey in Keys(object = object[[img]])) {
        imissing[[i]] <- gsub(
          pattern = paste0('^', lkey),
          replacement = '',
          x = imissing[[i]]
        )
      }
    }
    imissing <- names(x = imissing[imissing %in% Features(x = object[[img]])])
    keyed.mols[[img]] <- c(keyed.mols[[img]], imissing)
  }
  keyed.mols <- Filter(f = length, x = keyed.mols)
  keyed.mols <- sapply(X = keyed.mols, FUN = unname, simplify = FALSE)
  return(keyed.mols)
}

```


```{r}
genes<-rownames(seurat_object_3mon@assays$Nanostring)

color1000<-palette(rainbow(1000))

cellszoom<-imagecells(seurat_object_3mon, fov = "Run5738.msbrain", group.by = 'nb_clus',alpha = 0.1, axes = TRUE, border.color = "Black" ,mols.cols = color1000,cols=colors, mols.size = 0.000000000000000000000000000000001, molecules= genes ,dark.background = FALSE) + xlim(18750, 19750)+ ylim(c(-269100,-267950 ))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none")



ggsave("CellsAllGenes.png",cellszoom,width = 10, height = 10, units = "cm", path = flightpath_plot_dir)
```


Supplemental Figure 17A
```{r}
library(dplyr)
library(Seurat)
library(patchwork)



#if you need to install umap
#reticulate::py_install(packages ='umap-learn')


seurat_object_3mon_2<-seurat_object_3mon

seurat_object_3mon_2<-RunUMAP(seurat_object_3mon_2, dims = 1:10,  n.neighbors = 30L, min.dist = 0.01, spread = 0.5)

p<-DimPlot(seurat_object_3mon_2,cols=colors,label = FALSE, pt.size = 0.000001)


ggsave("UMAP_3month_nolabels.pdf", p,  width = 25, height = 15, units = "cm", path = flightpath_plot_dir)



```



Fig 8c




```{r}




cell_type_idents_3mon<-Idents(seurat_object_3mon)

pSyn_cell_ind2

cell_names_psyn_3mon<-c()
for( i in cell_type_idents_3mon[pSyn_cell_ind2]){
  new_name<-paste("psyn",i, sep="_")
  cell_names_psyn_3mon<-c(cell_names_psyn_3mon, new_name)
}

cell_names_psyn_3mon
cell_type_idents<-Idents(seurat_object_3mon)

cell_names_noPath_3mon<-c()
for( i in cell_type_idents[-pSyn_cell_ind2]){
  new_name<-paste("noPath",i, sep="_")
  cell_names_noPath_3mon<-c(cell_names_noPath_3mon, new_name)
}




cell_names_3mon<-c()
for(i in 1:length(Idents(seurat_object_3mon))){
  name1<-Idents(seurat_object_3mon)[i]
  if(i %in% pSyn_cell_ind2==TRUE){
    new_name<-paste("psyn",name1, sep="_")
     cell_names_3mon<-c(cell_names_3mon, new_name)
  }
  else{
     new_name<-paste("noPath",name1, sep="_")
  cell_names_3mon<-c(cell_names_3mon, new_name)
  }
}

```




```{r}
Idents(seurat_object_3mon)<-cell_names_3mon
```





Get barplot
```{r}


bargraph_data<-c()

bargraph_data$cell_names<-cell_names_3mon
bargraph_data$segment<- "NeuN"
bargraph_data<-as.data.frame(bargraph_data)

bargraph_data$segment[pSyn_cell_ind2]<-"pSyn"

bargraph_data$cell_names<-gsub("noPath_","",bargraph_data$cell_names)

bargraph_data$cell_names<-gsub("psyn_","",bargraph_data$cell_names)


bg_dat<-c()



bg_dat$pSyn<-"pSyn"
bg_dat$NeuN<-"NeuN"
bg_dat$celltype<- c("Astro","Endo","L2_3 IT CTX","L2_3 IT PPP",
                    "L4 RSP-ACA","L5 IT CTX","L5 PT CTX","L5_6 IT TPE-ENT",
                    "L5_6 NP CTX","L6 CT CTX","L6 IT CTX","L6b CTX","Lamp5",
                    "Micro-PVM","Oligo","Pvalb","Sncg","Sst","Sst Chodl","Vip")
bg_dat<-as.data.frame(bg_dat)

ind<-which(bargraph_data$segment=="pSyn")



ind1<-which(bargraph_data$cell_names[ind]=="Astro")
ind2<-which(bargraph_data$cell_names[ind]=="Endo")
ind3<-which(bargraph_data$cell_names[ind]=="L2_3 IT CTX")
ind4<-which(bargraph_data$cell_names[ind]=="L2_3 IT PPP")
ind5<-which(bargraph_data$cell_names[ind]=="L4 RSP-ACA")
ind6<-which(bargraph_data$cell_names[ind]=="L5 IT CTX")
ind7<-which(bargraph_data$cell_names[ind]=="L5 PT CTX")
ind8<-which(bargraph_data$cell_names[ind]=="L5_6 IT TPE-ENT")
ind9<-which(bargraph_data$cell_names[ind]=="L5_6 NP CTX")
ind10<-which(bargraph_data$cell_names[ind]=="L6 CT CTX")
ind11<-which(bargraph_data$cell_names[ind]=="L6 IT CTX")
ind12<-which(bargraph_data$cell_names[ind]=="L6b CTX")
ind13<-which(bargraph_data$cell_names[ind]=="Lamp5")
ind14<-which(bargraph_data$cell_names[ind]=="Micro-PVM")
ind15<-which(bargraph_data$cell_names[ind]=="Oligo")
ind16<-which(bargraph_data$cell_names[ind]=="Pvalb")
ind17<-which(bargraph_data$cell_names[ind]=="Sncg")
ind18<-which(bargraph_data$cell_names[ind]=="Sst")
ind19<-which(bargraph_data$cell_names[ind]=="Sst Chodl")
ind20<-which(bargraph_data$cell_names[ind]=="Vip")


vec1<-c(length(ind1),length(ind2),length(ind3),length(ind4),length(ind5),length(ind6),length(ind7),length(ind8),length(ind9),length(ind10),length(ind11),length(ind12),length(ind13),length(ind14),length(ind15),length(ind16),length(ind17),length(ind18),length(ind19),length(ind20))

bg_dat$pSyn<-vec1



ind1<-which(bargraph_data$cell_names[-ind]=="Astro")
ind2<-which(bargraph_data$cell_names[-ind]=="Endo")
ind3<-which(bargraph_data$cell_names[-ind]=="L2_3 IT CTX")
ind4<-which(bargraph_data$cell_names[-ind]=="L2_3 IT PPP")
ind5<-which(bargraph_data$cell_names[-ind]=="L4 RSP-ACA")
ind6<-which(bargraph_data$cell_names[-ind]=="L5 IT CTX")
ind7<-which(bargraph_data$cell_names[-ind]=="L5 PT CTX")
ind8<-which(bargraph_data$cell_names[-ind]=="L5_6 IT TPE-ENT")
ind9<-which(bargraph_data$cell_names[-ind]=="L5_6 NP CTX")
ind10<-which(bargraph_data$cell_names[-ind]=="L6 CT CTX")
ind11<-which(bargraph_data$cell_names[-ind]=="L6 IT CTX")
ind12<-which(bargraph_data$cell_names[-ind]=="L6b CTX")
ind13<-which(bargraph_data$cell_names[-ind]=="Lamp5")
ind14<-which(bargraph_data$cell_names[-ind]=="Micro-PVM")
ind15<-which(bargraph_data$cell_names[-ind]=="Oligo")
ind16<-which(bargraph_data$cell_names[-ind]=="Pvalb")
ind17<-which(bargraph_data$cell_names[-ind]=="Sncg")
ind18<-which(bargraph_data$cell_names[-ind]=="Sst")
ind19<-which(bargraph_data$cell_names[-ind]=="Sst Chodl")
ind20<-which(bargraph_data$cell_names[-ind]=="Vip")


vec2<-c(length(ind1),length(ind2),length(ind3),length(ind4),length(ind5),length(ind6),length(ind7),length(ind8),length(ind9),length(ind10),length(ind11),length(ind12),length(ind13),length(ind14),length(ind15),length(ind16),length(ind17),length(ind18),length(ind19),length(ind20))


bg_dat$NeuN<-vec2


neun_total<-sum(bg_dat$NeuN)
pSyn_total<-sum(bg_dat$pSyn)




psyn_percent<-c()
for( i in bg_dat$pSyn){
  vec1<-i/pSyn_total
  psyn_percent<-c(psyn_percent,vec1)
}
neun_percent<-c()
for( i in bg_dat$NeuN){
  vec1<-i/neun_total
  neun_percent<-c(neun_percent,vec1)
}
bg_dat2<-c()

bg_dat2$celltype<-bg_dat$celltype

bg_dat2$`pSyn%`<-psyn_percent

bg_dat2$`NeuN%`<-neun_percent

bg_dat2<-as.data.frame( bg_dat2)

library(reshape2)

bg_melt2<-melt(bg_dat2)


names(colors)<-c("Oligo","L6b CTX","L5 PT CTX" ,"L5 IT CTX", "Sncg","Lamp5", "L6 CT CTX", "Astro",  "Sst" , "Pvalb" ,  "L6 IT CTX", "Sst Chodl", "Vip", "L2_3 IT PPP", "L2_3 IT CTX" , "L5_6 NP CTX","L4 RSP-ACA","Micro-PVM", "L5_6 IT TPE-ENT", "Endo")

bar_color<-c(1:length(bg_melt2$celltype))

for(i in unique(bg_melt2$celltype)){
  print(i)
  ind<-which(bg_melt2$celltype==i)
  if (length(grep(i,names(colors))) > 1){
    ind2<-which(grepl(i,names(colors)) & !grepl(" ",names(colors)))
  } else {
    ind2<-which(grepl(i,names(colors)))
  }
  vec<-colors[ind2]
  bar_color[ind]<-vec
}


p <- ggplot(bg_melt2, aes(fill=celltype, x=variable, y=value)) + 
    geom_bar(position="stack", stat="identity")+scale_fill_manual(values=colors)+ 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.key.size = unit(0.4,'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.2, 'cm'), #change legend key width
        legend.title = element_text(size=8), #change legend title font size
        legend.text = element_text(size=6))
  

ggsave("Cell_Proportion_barplot_3mon.pdf", p,  width = 8, height = 10, units = "cm",path = flightpath_plot_dir)

ggsave("Cell_Proportion_barplot.pdf",  width = 50, height = 30, units = "cm",path = flightpath_plot_dir)



```



Fig 8d

```{r}

#This version of Seurat is required to reproduce this figure.
#remotes::install_version("Seurat", version = "4.4.0")

library(MAST)
library(Seurat)



results_L5ItpsynNoPath <- FindMarkers(object = seurat_object_3mon, ident.1= "noPath_L5 IT CTX", test.use = "MAST", thresh.use=0)


results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val <0.05 & 
                               results_L5ItpsynNoPath$avg_log2FC >0]<- paste(
                                 "Decreased in pSyn+ L5 IT Neurons P < 0.05")
results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val_adj <0.05 & 
                               results_L5ItpsynNoPath$avg_log2FC >0]<- paste(
                                 "Decreased in pSyn+ L5 IT Neurons FDR < 0.05")
results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val_adj <0.01 & 
                               results_L5ItpsynNoPath$avg_log2FC >0]<- paste(
                                 "Decreased in pSyn+ L5 IT Neurons FDR < 0.01")
results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val <0.05 & 
                               results_L5ItpsynNoPath$avg_log2FC <0]<- paste(
                                 "Increased in pSyn+ L5 IT Neurons P < 0.05")
results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val_adj <0.05 & 
                               results_L5ItpsynNoPath$avg_log2FC <0]<- paste(
                                 "Increased in pSyn+ L5 IT Neurons FDR < 0.05")
results_L5ItpsynNoPath$color[results_L5ItpsynNoPath$p_val_adj <0.01 & 
                               results_L5ItpsynNoPath$avg_log2FC <0]<- paste(
                                 "Increased in pSyn+ L5 IT Neurons FDR < 0.01")

results_L5ItpsynNoPath$color[abs(results_L5ItpsynNoPath$avg_log2FC) < 0.25] <- "NS or FC < 0.5"





results_L5ItpsynNoPath$gene<-rownames(results_L5ItpsynNoPath)

results_L5ItpsynNoPath$invert_P <- (-log10(results_L5ItpsynNoPath$p_val)) * sign(results_L5ItpsynNoPath$avg_log2FC)

  top_g <- c()
top_g <- c(top_g,
  results_L5ItpsynNoPath[, 'gene'][order(results_L5ItpsynNoPath[, 'invert_P'], decreasing = TRUE)[1:10]],
  results_L5ItpsynNoPath[, 'gene'][order(results_L5ItpsynNoPath[, 'invert_P'], decreasing = FALSE)[1:10]])
  top_g <- unique(top_g) 
  

highlight_top_g<-subset(results_L5ItpsynNoPath, gene %in% top_g & p_val <0.05 &  color != "NS or FC < 0.5")  
  
colors<-c( "darkslategray3","darkslategray2", "darkslategray1","darkseagreen3", "darkseagreen2", "darkseagreen1", "gray" )

names(colors)<-c("Increased in pSyn+ L5 IT Neurons P < 0.05", "Increased in pSyn+ L5 IT Neurons FDR < 0.05", "Increased in pSyn+ L5 IT Neurons FDR < 0.01", "Decreased in pSyn+ L5 IT Neurons P < 0.05","Decreased in pSyn+ L5 IT Neurons FDR < 0.05", "Decreased in pSyn+ L5 IT Neurons FDR < 0.01","NS or FC < 0.5") 

results_L5ItpsynNoPath <- results_L5ItpsynNoPath[results_L5ItpsynNoPath$color != "NS or FC < 0.5",]
    
diff_exp3<-ggplot(results_L5ItpsynNoPath,
       aes(x = avg_log2FC, y = -log10(`p_val`),
           color = color, label = gene)) +
    geom_vline(xintercept = c(0.5, -0.5), lty = "dashed", size=0.2) +
    geom_hline(yintercept = -log10(0.05), lty = "dashed", size=0.2) +
    geom_point(size=0.0000000000000000000000000001, alpha=0.5) +
    labs(x = "log2(FC)",
         y = "Significance, -log10(P)",
         color = "Key") +
    scale_color_manual(values = colors,
                                  guide = guide_legend(override.aes = list(size = 0.5))) +
    scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
    geom_text_repel(data = subset(results_L5ItpsynNoPath, gene %in% top_g),
                    #& P<0.05) & Color != "NS or FC < 0.5"),
                    size = 1.5, point.padding = 0.1, color = "black",
                    min.segment.length = .3, box.padding = .1, lwd = .2,
                    max.overlaps = 50, segment.size=0.05, force = 10, max.time = 3) +
    theme_bw(base_size = 6) +
  theme(axis.line = element_line(color='black'),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank())+
    theme(legend.position = "bottom",
          legend.key.size= unit(0.00001, 'cm'),
          legend.title = element_text(size = 2),
          legend.text = element_text(size=2),
          legend.key.height = unit(0.3, 'cm'),
          legend.key.width = unit(3, 'cm')) +
  geom_point(data=highlight_top_g, alpha=0.9, size=0.5)



diff_exp3
    
    
    
ggsave(plot=diff_exp3, file="volc_L5ITPSYNNoPath.pdf", width = 14, height = 7, units = "cm", path = flightpath_plot_dir)

```




If you would like to replicate figure 8E, please refer to the Mouse GeoMx pipeline, the code to produce this image is in the Mouse GeoMx pipeline. 
























